In [1]:
import pandas as pd

# Load the student performance dataset
pd.read_csv(r"C:\Users\HP\Documents\GitHub\Beta-Anvil\student-performance-analysis\data\StudentsPerformance.csv")
# Preview the first 5 rows

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

I just learnt how to load a full dataset

In [4]:
import pandas as pd

data = pd.read_csv(r"C:\Users\HP\Documents\GitHub\Beta-Anvil\student-performance-analysis\data\StudentsPerformance.csv")

data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

I just learnt how to clean my data

In [5]:
student1 = data["math score"][0]
student2 = data["math score"][1]
student3 = data["math score"][2]

total_score = student1 + student2 + student3

print("Total of first 3 students:", total_score)

Total of first 3 students: 231

i just learnt hoe to store the data,separate the data and get the sum of the data

In [6]:
math_scores = list(data["math score"])

pass_count = 0

for score in math_scores:
    if score >= 50:
        pass_count += 1

print("Number of students that passed:", pass_count)

Number of students that passed: 865

so i was able to learn how to Convert pandasto a Python list

i was able to understand the concept of Looping through dataset

And also to learn the Conditional counting logic

In [7]:
first_five_scores = list(data["math score"][:5])

for score in first_five_scores:
    if score >= 50:
        print("Pass")
    else:
        print("Fail")

Pass
Pass
Pass
Fail
Pass

this concept has just thought me how to distinguish and print based on scores if the student passed the course of failed the course

In [8]:
first_ten_scores = list(data["math score"][:10])

pass_count = 0

for score in first_ten_scores:
    if score >= 50:
        pass_count += 1

print("Number of students that passed (first 10):", pass_count)

Number of students that passed (first 10): 7

Challenge response